const QUESTIONS = [
  'Give up social media or eat the same dinner for the rest of your life?',
  'Lose all of the money you’ve earned this year or lose all of the memories you’ve gained this year?',
  'Have no taste or be colorblind?',
  'Know the date of your death or the cause of your death?',
  'Flip a coin for a chance to win $20 or immediately win $10?',
  'Always hit a red light for the rest of your life or always get slow internet after the sun goes down?',
  'Have the lights on or off if you knew the room was full of snakes?',
  'Be the person who flips the switch during executions or be the judge who decides who should be executed?',
  'Go blind or deaf?',
  'Be married to someone good-looking who doesn’t think you’re attractive or be married to someone ugly who thinks you’re gorgeous?',
  'Win $25,000 or have your best friend win $100,000?',
  'Work a high-paying job that you hate or your dream job with only enough money for basic necessities?',
  'Wake up in your underwear at work or wake up naked in the woods 20 miles from home?',
  'Find $100 floating in a public toilet or $5 in your pocket?',
  'Be able to read someone’s mind or control their mind?',
  'Look at your mom’s search history or your dad’s search history?',
  'Let your parents access your browsing history or your boss?',
  'Fight a chicken to the death every time you get into a car or fight an orangutan to the death once a year, but you get a sword?',
  'Get a text from a one-night stand that says “I’m pregnant” or “I have an incurable STD”?',
  'Forget your favorite books so you can reread them again for the first time or forget your favorite movies so you can rewatch them for the first time?',
  'Always be 20 minutes late for important events or always be 2 hours early to everything else?',
  'Always feel the urge to pee or never know when you have to pee (always wear a diaper)?',
  'Find a dead body or be a witness to a deadly assault?',
  'Only be able to wash your hair twice a year or only be able to check your phone once a day?',
  'Eat a live worm or be locked in a room with a tarantula for an hour (but not know where the tarantula is)?',
  'Be able to change the future or the past, just by imagining it?',
  'Have thought bubbles appear over your head for everyone to see or for everyone you know to have access to your search history?',
  'Be 4 years old your entire life or be 90 years old your entire life?',
  'Save 3 of your closest family members or 1,000 people you don’t know?',
  'Have a lot of mediocre friends or only one really good friend?',
  'Smack a puppy or get smacked by your dad in public?',
  'Turn pink every time someone said “hello” or get really angry every time someone said “bless you”?',
  'Date the hottest person in the world but not be able to have sex with them or date an ugly person that you can have sex with?',
  'Give up your salary for the next five years or give up everything you have in the bank right now?',
  'Lose all your teeth or lose a day of your life every time you kissed someone?',
  'Would you rather have sex with your cousin in secret or not have sex with your cousin but everyone thinks you did?',
  'Wake up in the middle of a good dream every time and not be able to fall back to sleep or never be able to wake yourself up from a nightmare?',
  'Give up cursing forever or give up ice cream for 10 years?',
  'If you were stranded on an island with no food with you dog and your sibling, would you kill your dog to feed your sibling or let your sibling die of hunger?',
  'Always have tangled hair or always have wet underarms?',
  'Get a pimple the night before important dates or get sick every time after a important date is over?',
  'Lose all of your friends but win the lottery or keep your friends but you don’t get a raise for the rest of your life?',
  'Talk to animals or speak all human languages?',
  'Be reborn into the past or the future?',
  'Be able to run 200 miles an hour or be able to fly 20 miles an hour?',
  'Give up your favorite food or give up sex?',
  'Eat dinner alone for a year or have to take showers at a public gym for a year?',
  'Die before your spouse or after?',
  'Get stranded on Antarctica or in the desert?',
  'Give up brushing your teeth or brushing your hair?',
  'Win the lottery or live—in good health—to be 200 years old?',
  'Never age physically or never age mentally?',
  'Be able to play every musical instrument or master every type of sport?',
  'Be a vegetarian or only be able to eat meat?',
  'Have no friends but be rich or have lots of friends but be dirt poor?',
  'Marry the person of your dreams or have the job of your dreams?',
  'Have a pause button in your life or a rewind button?',
  'Have your parents walk in on you while you were doing it or accidentally walk in on them doing it?',
  'Fart out loud during a presentation or snort while laughing on a great first date?',
  'Always be overdressed or always be underdressed?',
  'Drown to death burned to death?',
  'Constantly itch or be in excruciating pain for a whole day once a year?',
  'Always have full battery for your phone or always have a full tank of gas for your car?',
];

export default QUESTIONS;
